static const char black[]       = "#2b3339";
static const char gray2[]       = "#323c41"; // unfocused window border
static const char gray3[]       = "#323c41";
static const char gray4[]       = "#7fbbb3";
static const char blue[]        = "#7fbbb3";  // focused window border
static const char green[]       = "#83c092";
static const char red[]         = "#e67e80";
static const char orange[]      = "#dbbc7f";
static const char yellow[]      = "#dbbc7f";
static const char pink[]        = "#d699b6";
static const char col_borderbar[]  = "#2b3339"; // inner border
