static const char black[]       = "#282828";
static const char gray2[]       = "#655b53"; // unfocused window border
static const char gray3[]       = "#655b53";
static const char gray4[]       = "#655b53";
static const char blue[]        = "#448488";  // focused window border
static const char green[]       = "#689d69";
static const char red[]         = "#cc231c";
static const char orange[]      = "#fabc2e";
static const char yellow[]      = "#fabc2e";
static const char pink[]        = "#b16185";
static const char col_borderbar[]  = "#282828"; // inner border
