static const char black[]       = "#0f101a";
static const char gray2[]       = "#282a40"; // unfocused window border
static const char gray3[]       = "#181a29";
static const char gray4[]       = "#282a40";
static const char blue[]        = "#93bbff";  // focused window border
static const char green[]       = "#cdea9f";
static const char red[]         = "#F07178";
static const char orange[]      = "#ffd47e";
static const char yellow[]      = "#ffee7e";
static const char pink[]        = "#d3a7ee";
static const char col_borderbar[]  = "#0f101a"; // inner border
