static const char black[]       = "#1a1b26";
static const char gray2[]       = "#1f2335"; // unfocused window border
static const char gray3[]       = "#292e42";
static const char gray4[]       = "#545c7e";
static const char blue[]        = "#7aa2f7";  // focused window border
static const char green[]       = "#9ece6a";
static const char red[]         = "#f7768e";
static const char orange[]      = "#ff9e64";
static const char yellow[]      = "#e0af68";
static const char pink[]        = "#bb9af7";
static const char col_borderbar[]  = "#1a1b26"; // inner border
